# Generated by Django 3.1.2 on 2020-10-25 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('ssn', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('company_id', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSpecifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.baseuser')),
                ('rate', models.IntegerField()),
                ('credit', models.IntegerField()),
            ],
            bases=('crm.baseuser',),
        ),
        migrations.CreateModel(
            name='ScreenOwner',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.baseuser')),
                ('rate', models.IntegerField()),
                ('credit', models.IntegerField()),
            ],
            bases=('crm.baseuser',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.baseuser')),
            ],
            bases=('crm.baseuser',),
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.screenspecifications')),
                ('screenowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.screenowner')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('frequency', models.IntegerField()),
                ('price', models.IntegerField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.advertiser')),
                ('screen_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.screenowner')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('media_url', models.URLField()),
                ('length', models.DurationField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.advertiser')),
            ],
        ),
    ]
